name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%y%m%d')"

    - name: Create config.yml
      run: |
        echo "${{ secrets.CONFIG_YML }}" > ./backend/config.yml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: joosum.kr.ncr.ntruss.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64
        tags: joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }}
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to VM
      env:
        VM_HOST: ${{ secrets.VM_HOST_IP }}
        VM_USERNAME: root
        VM_PORT: 22
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
      run: |
        echo $VM_PASSWORD | sshpass ssh -o StrictHostKeyChecking=no -p $VM_PORT $VM_USERNAME@$VM_HOST <<EOF
          docker pull joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }}
          docker stop $(docker ps -q -f 'expose=5001')
          docker rm $(docker ps -aq -f 'expose=5001')
          docker run -d -v /etc/ssl/certs:/etc/ssl/certs -p 5001:5001 joosum.kr.ncr.ntruss.com/joosum-backend:${{ steps.date.outputs.date }}
        EOF
