name: Send FCM Notification about unread link

on:
  schedule:
    # UTC 로 실행됨. UTC + 9 = KST
    # 매주 월요일 19:00
    - cron: '0 10 * * 1'

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create config.yml
        run: |
          echo "${{ secrets.CONFIG_YML }}" > backend/cmd/scheduler/config.yml

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and run Go application for Notification
        run: |
          cd backend/cmd/scheduler
          go build
          ./scheduler unread
